//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab13var17
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public byte[] Image { get; set; }
        public int Age { get; set; }
        public string Soldier { get; set; }
    }
}
